package com.cimen.ways.component.gateway.service.launcher.model;

import java.io.Serializable;

public class GatewayRouteConfig implements Serializable {
    /**
     * <pre>
     * 路由编号
     * 表字段 : ways_gateway_route_config.route_id
     * </pre>
     */
    private Integer routeId;

    /**
     * <pre>
     * 映射路径
     * 表字段 : ways_gateway_route_config.path
     * </pre>
     */
    private String path;

    /**
     * <pre>
     * 服务标识
     * 表字段 : ways_gateway_route_config.service_id
     * </pre>
     */
    private String serviceId;

    /**
     * <pre>
     * 服务地址
     * 表字段 : ways_gateway_route_config.url
     * </pre>
     */
    private String url;

    /**
     * <pre>
     * 是否启用
     * 表字段 : ways_gateway_route_config.enabled
     * </pre>
     */
    private Short enabled;

    /**
     * <pre>
     * 排序值,数值越小,优先级越高
     * 表字段 : ways_gateway_route_config.sort
     * </pre>
     */
    private Integer sort;

    /**
     * <pre>
     * 
     * 表字段 : ways_gateway_route_config.lb
     * </pre>
     */
    private String lb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ways_gateway_route_config
     *
     * Auto-Generator
     */
    private static final long serialVersionUID = 1L;

    /**
     * <pre>
     * 获取：路由编号
     * 表字段：ways_gateway_route_config.route_id
     * </pre>
     *
     * @return ways_gateway_route_config.route_id：路由编号
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * <pre>
     * 设置：路由编号
     * 表字段：ways_gateway_route_config.route_id
     * </pre>
     *
     * @param routeId
     *            ways_gateway_route_config.route_id：路由编号
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * <pre>
     * 获取：映射路径
     * 表字段：ways_gateway_route_config.path
     * </pre>
     *
     * @return ways_gateway_route_config.path：映射路径
     */
    public String getPath() {
        return path;
    }

    /**
     * <pre>
     * 设置：映射路径
     * 表字段：ways_gateway_route_config.path
     * </pre>
     *
     * @param path
     *            ways_gateway_route_config.path：映射路径
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * <pre>
     * 获取：服务标识
     * 表字段：ways_gateway_route_config.service_id
     * </pre>
     *
     * @return ways_gateway_route_config.service_id：服务标识
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * <pre>
     * 设置：服务标识
     * 表字段：ways_gateway_route_config.service_id
     * </pre>
     *
     * @param serviceId
     *            ways_gateway_route_config.service_id：服务标识
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId == null ? null : serviceId.trim();
    }

    /**
     * <pre>
     * 获取：服务地址
     * 表字段：ways_gateway_route_config.url
     * </pre>
     *
     * @return ways_gateway_route_config.url：服务地址
     */
    public String getUrl() {
        return url;
    }

    /**
     * <pre>
     * 设置：服务地址
     * 表字段：ways_gateway_route_config.url
     * </pre>
     *
     * @param url
     *            ways_gateway_route_config.url：服务地址
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * <pre>
     * 获取：是否启用
     * 表字段：ways_gateway_route_config.enabled
     * </pre>
     *
     * @return ways_gateway_route_config.enabled：是否启用
     */
    public Short getEnabled() {
        return enabled;
    }

    /**
     * <pre>
     * 设置：是否启用
     * 表字段：ways_gateway_route_config.enabled
     * </pre>
     *
     * @param enabled
     *            ways_gateway_route_config.enabled：是否启用
     */
    public void setEnabled(Short enabled) {
        this.enabled = enabled;
    }

    /**
     * <pre>
     * 获取：排序值,数值越小,优先级越高
     * 表字段：ways_gateway_route_config.sort
     * </pre>
     *
     * @return ways_gateway_route_config.sort：排序值,数值越小,优先级越高
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * <pre>
     * 设置：排序值,数值越小,优先级越高
     * 表字段：ways_gateway_route_config.sort
     * </pre>
     *
     * @param sort
     *            ways_gateway_route_config.sort：排序值,数值越小,优先级越高
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * <pre>
     * 获取：
     * 表字段：ways_gateway_route_config.lb
     * </pre>
     *
     * @return ways_gateway_route_config.lb：
     */
    public String getLb() {
        return lb;
    }

    /**
     * <pre>
     * 设置：
     * 表字段：ways_gateway_route_config.lb
     * </pre>
     *
     * @param lb
     *            ways_gateway_route_config.lb：
     */
    public void setLb(String lb) {
        this.lb = lb == null ? null : lb.trim();
    }

    /**
     *
     * @param that
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GatewayRouteConfig other = (GatewayRouteConfig) that;
        return (this.getRouteId() == null ? other.getRouteId() == null : this.getRouteId().equals(other.getRouteId()))
            && (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()))
            && (this.getServiceId() == null ? other.getServiceId() == null : this.getServiceId().equals(other.getServiceId()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getEnabled() == null ? other.getEnabled() == null : this.getEnabled().equals(other.getEnabled()))
            && (this.getSort() == null ? other.getSort() == null : this.getSort().equals(other.getSort()))
            && (this.getLb() == null ? other.getLb() == null : this.getLb().equals(other.getLb()));
    }

    /**
     *
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRouteId() == null) ? 0 : getRouteId().hashCode());
        result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
        result = prime * result + ((getServiceId() == null) ? 0 : getServiceId().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getEnabled() == null) ? 0 : getEnabled().hashCode());
        result = prime * result + ((getSort() == null) ? 0 : getSort().hashCode());
        result = prime * result + ((getLb() == null) ? 0 : getLb().hashCode());
        return result;
    }

    /**
     *
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", routeId=").append(routeId);
        sb.append(", path=").append(path);
        sb.append(", serviceId=").append(serviceId);
        sb.append(", url=").append(url);
        sb.append(", enabled=").append(enabled);
        sb.append(", sort=").append(sort);
        sb.append(", lb=").append(lb);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}